### ISSUE TITLE
Event calendar widget

### ISSUE THREAD

**Issue by jaredatch** [billerickson/BE-Events-Calendar#17]
https://github.com/billerickson/BE-Events-Calendar/commit/c74e281a0d263dc13de55b1a1e80cac63a1d0171

http://cl.ly/image/2U3g0W440x1V

This feature should be working well, however in its current iteration there is one down side: right now events only show up on the day they start. So if it is a 3 day festival running from Friday-Sunday on the calendar only Friday will be highlighted and listed. So that needs to be fixed, other than that I think it is solid.

**Comment by billerickson** [comment]
Added it, along with some other changes
