### ISSUE TITLE
Activation hook

### ISSUE THREAD

**Issue by ryanhellyer** [billerickson/BE-Events-Calendar#20]
Firstly, this is an excellent events calendar library. Thanks for sharing it :)

I did find that the activation hook does not fire though. It also doesn't flush the permalinks correctly, as the post-type hasn't loaded before the flushing occurs. You can fix the second issue by directly firing the post type method from within the activation method.

https://github.com/billerickson/BE-Events-Calendar/blob/master/inc/events.php

**Comment by billerickson** [comment]
Thanks, this was overlooked when we moved everything out of the main plugin file. 

Is there a cleaner way to register the activation hook without creating an additional constant?

**Comment by ryanhellyer** [comment]
I think the only other way would be to use __FILE__ wrapped in dirname() and then manually adding the PHP file back in. I bounce between the two different approaches depending on my mood.
