### ISSUE TITLE
Featured images and excerpts

### ISSUE THREAD

**Issue by redblueconcepts** [billerickson/BE-Events-Calendar#24]
Bill, I noticed that if I enable featured images and/or thumbnails for both events and for recurring-events, that information does not get copied when recurring events are generated or regenerated.

Is this something that's possible to do? I assume the same thing would apply to other meta information that's added to both events and recurring events, but I don't know that particular detail for sure.

This would be useful in that some organizations use those things (other meta, excerpts, and post thumbnails), and it becomes a manual process to update those after creating a set of events.

I think it would be possible to work around by using the events template to figure out the corresponding recurring-event, then pulling the information from there; however, that's kind of a duct-taped solution.

**Comment by billerickson** [comment]
You can use the `be_events_manager_recurring_meta` filter to add additional post meta to be saved. For instance, this should add the featured image:

```php

function ea_featured_image_recurring( $meta ) {
$meta[] = '_thumbnail_id';
return $meta;
}
add_filter( 'be_events_manager_recurring_meta', 'ea_featured_image_recurring' );
```

See the responsible code in plugin here: https://github.com/billerickson/BE-Events-Calendar/blob/master/inc/events-recurring.php#L422-L458

Let me know if there's something else needed here.
