### ISSUE TITLE
Apply Featured Image from Recurring Event Setup to all created Events

### ISSUE THREAD

**Issue by hirejordansmith** [billerickson/BE-Events-Calendar#26]
Hi Bill,

First off, thanks for this plugin! I really appreciate it!

I noticed that you guys may be combining the Recurring Events and Events posts types soon so this might not be super useful but I added support for mapping the featured image from a recurring event to each individual event that is created and wanted to share it with you or others who may need this functionality.

Also wanted to run it by you in case there are any things that I may have overlooked with this. I have a working but far from intimate understanding of this stuff. :-)

Line 100 - add 'thumbnail' to supports for register_post_type()
Line 411 - set $event_thumb_id variable
Line 438 - mapping thumbnail to event

https://gist.github.com/hirejordansmith/3a78a357c0c4a72f2f2c183501bae26c

**Comment by billerickson** [comment]
This is how I would implement this without modifying the core plugin: https://gist.github.com/billerickson/8246696522d6735a36ecb2864d756c0f

First we filter the post type arguments, adding support for 'thumbnail'. Then when we are generating new events we use the `be_events_manager_recurring_meta` filter to include `_thumbnail_id` as one of the meta that's copied over. 

This is the same filter you can use for any other metadata you want to add to events (location, price...).

**Comment by hirejordansmith** [comment]
Ah perfect! Thanks so much Bill!
