### ISSUE TITLE
Use the proper filter to customize the post type title placeholder

### ISSUE THREAD

**Issue by benoitchantre** [billerickson/BE-Events-Calendar#32]
Instead of using an action hook on `get_text`, the post type title placeholder should be customized using a filter on [`enter_title_here`](https://developer.wordpress.org/reference/hooks/enter_title_here/).

**Comment by billerickson** [comment]
Oh nice! I didn't know about that filter.

I'm also planning to address the other issues you've submitted in the next few days. I've just been busy with a client project.

**Comment by benoitchantre** [comment]
Here's the refactored method.
I'll submit a PR, but I don't know if the inline documentation is correct like that.

```PHP
/**
 * Change the default title placeholder text
 *
 * @since 1.0.0
 * @param string $title
 * @return string Customized translation for title
 */
function title_placeholder( $title ) {

	$screen = get_current_screen();

	if  ( 'events' === $screen->post_type ) {
		$title = 'Enter Event Name Here';
	}

	return $title;
}
```
