### ISSUE TITLE
Undefined variables in widget-upcoming-events.php

### ISSUE THREAD

**Issue by benoitchantre** [billerickson/BE-Events-Calendar#36]
`$before_widget`, `$after_widget`, `$before_title` and `$after_title`are undefined.

They are located in `widget()`, the function that outputs the HTML of the widget.

**Comment by billerickson** [comment]
They are created by [this line](https://github.com/billerickson/BE-Events-Calendar/blob/master/inc/widget-upcoming-events.php#L33).

**Comment by benoitchantre** [comment]
Thanks, I haven't seen that.
