### ISSUE TITLE
Event category rewrite should not be prepended with front base

### ISSUE THREAD

**Issue by benoitchantre** [billerickson/BE-Events-Calendar#46]
Events are not prepended with front base, we should be consistent with rewrite args.

**Comment by billerickson** [comment]
Why did you close the pull request associated with this? I agree, the taxonomy rewrite should have `'with_front' => false`

**Comment by benoitchantre** [comment]
I'll submit it again (tomorrow), this was a bad manipulation.

**Comment by benoitchantre** [comment]
@billerickson The PR has been reopened.
