### ISSUE TITLE
Event location

### ISSUE THREAD

**Issue by benoitchantre** [billerickson/BE-Events-Calendar#52]
I think a location information is often needed with an event. This could be added as a custom taxonomy and displayed depending on theme support.

Term title and description could be enough for a first implementation.
Term metas could be added later to support coordinates or an URL.

What are your opinions on this @billerickson?
Would you accept a PR?

**Comment by billerickson** [comment]
Yes, I can see that being useful, as long as it's disabled by default and turned on in the same method as the event categories. Ex: `add_theme_support( 'be-events-calendar', array( 'event-location' ) );`

**Comment by benoitchantre** [comment]
Great. I'm already working on it.
