### ISSUE TITLE
Recurring events should be private

### ISSUE THREAD

**Issue by benoitchantre** [billerickson/BE-Events-Calendar#57]
The `recurring_event` post type is used to create `event` posts based based on recursion settings. I think there's no reason to have a `recurring_event` public. Visitors should only see events.

The downside of that change would be that plugins based on public value like Yoast SEO will not behave the same way.

What are your opinions @billerickson?

**Comment by billerickson** [comment]
I agree, `recurring_event` shouldn't be public. It's more of a helper tool for generating `event` posts than a standalone post type.
